version: '2'
services:

  #sonarqube:

  #    build:
  #      context: sonarqube/
  #    ports:
  #      - 9000:9000
  #    container_name: sonarqube

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /keystore:/keystore

  #    depends_on:
  #      - sonarqube
    networks:
      - webnet

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=snapanonyme
      - MYSQL_PASSWORD=snapanonyme
      - MYSQL_DATABASE=snapanonyme
    ports:
      - 3307:3306
    command:  mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - webnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - webnet

 # app:
  #  build:
   #   context: .
   # image: snapanonyme
   # ports:
    #  - 9010:9010
    #depends_on:
     # - mysql
    #networks:
     # - webnet
networks:
  webnet:



