spring:
  application:
    name: zerodash
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  ## Hibernate Logging
  logging:
    level:
      org.hibernate.SQL: DEBUG
  ## Internationalization
  messages:
    basename: i18n/messages

  ## Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: philippesimo@zerofiltre.tech  #Replace this field with your Gmail username.
    password: pcyhubgnlyivpplk           #Mail app password.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

#Custom properties
zerodash:
  email:
    from: hello@zerodash.tech
    base-url: http://51.178.60.37:32000
  security:
    jwt:
      header: Authorization
      prefix: Bearer
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      secret: JwtSecretKey
server:
  port: 9010