spring:
  application:
    name: zerodash
  datasource:
    url: jdbc:mysql://192.168.99.100:3307/zerodash?createDatabaseIfNotExist=true
    username: zerodash
    password: zerodash

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  ## Hibernate Logging
  logging:
    level:
      org.hibernate.SQL: DEBUG
  devtools:
    restart:
      additional-paths: resources/**

  ## Internationalization
  messages:
    basename: i18n/messages

  ## Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: kilosavendre@gmail.com  #Replace this field with your Gmail username.
    password: zgdciolpywkazafb           #Replace this field with your Gmail password.
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 9010

#Custom properties
zerodash:
  email:
    from: hello@zerodash.tech
    base-url: http://localhost:9010
  security:
    jwt:
      header: Authorization
      prefix: Bearer
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      secret: JwtSecretKey
